superdesk/superdesk-analytics

client/activity_reports/services/ActivityChart.js
client/activity_reports/services/ActivityReport.js
client/content_quota_report/services/ContentQuotaReport.js
client/controllers/AnalyticsController.js
client/index.js
client/processed_items_report/services/ProcessedItemsChart.js
client/source_category_report/directives/SourceCategoryReportContainer.js
client/source_category_report/directives/SourceCategoryReportPanel.js
client/source_category_report/directives/SourceCategoryReportView.js
client/source_category_report/directives/index.js
client/source_category_report/index.js
client/source_category_report/services/SourceCategoryChart.js
client/source_category_report/services/SourceCategoryReport.js
client/source_category_report/services/index.js
client/source_category_report/views/source-category-report-panel.html
client/source_category_report/views/source-category-report-view.html
client/source_category_report/views/source-category-report.html
client/styles/analytics.scss
client/utils.js
client/views/analytics.html
package.json
server/analytics/__init__.py
server/analytics/aggregations.py
server/analytics/source_category_report.py
server/features/processed_items_report.feature

* Document directives/services/methods
* Ability to choose a relative date range
* Copied changes for content_quota_reports endpoint from superdesk/superdesk-analytics#34 to allow behave tests to pass

[SDESK-2933] New report for Category/Source

---

.eslintrc.json
.gitignore
client/directives/AnalyticsContainer.js
client/index.js
client/saved_reports/directives/SaveGenerateReport.js
client/saved_reports/directives/SaveReportForm.js
client/saved_reports/directives/SavedReportItem.js
client/saved_reports/directives/SavedReportList.js
client/saved_reports/directives/index.js
client/saved_reports/index.js
client/saved_reports/services/SavedReportsService.js
client/saved_reports/services/index.js
client/saved_reports/styles/saved_reports.scss
client/saved_reports/tests/SavedReportsService.spec.js
client/saved_reports/views/save-generate-report.html
client/saved_reports/views/save-report-form.html
client/saved_reports/views/saved-report-item.html
client/saved_reports/views/saved-report-list.html
client/source_category_report/controllers/SourceCategoryController.js
client/source_category_report/views/source-category-report-chart-options.html
client/source_category_report/views/source-category-report-filters.html
client/source_category_report/views/source-category-report-panel.html
client/source_category_report/views/source-category-report-parameters.html
client/styles/analytics.scss
client/utils.js
server/analytics/__init__.py
server/analytics/saved_reports.py
server/features/saved_reports.feature
webpack.config.js

* Currently only implemented for the Source/Category report

[SDESK-3172] Generic functionality to save report parameters

---

.travis.yml
README.md
server/analytics/reports/__init__.py
server/analytics/reports/generate_report_test.py
server/analytics/reports/highcharts_server.py
server/scripts/install-highcharts-export-server.sh
server/settings.py

* This allows the API to use Highcharts to generate reports on the server

[SDESK-3173] Install and run the highcharts export server

---

client/source_category_report/services/SourceCategoryChart.js
server/analytics/source_category_report.py

* Will be fixed in future Highcharts release, see:
1. https://github.com/highcharts/highcharts/issues/866
2. https://github.com/highcharts/highcharts/commit/0903bb946edb6a537eb42822f59b95c762ae1892

[SDESK-3291] Fix Highcharts bug causing pie charts to not render

---

client/saved_reports/directives/SavedReportList.js
client/saved_reports/services/SavedReportsService.js
client/search/services/SearchReport.js
client/source_category_report/controllers/SourceCategoryController.js
client/source_category_report/views/source-category-report-filters.html
client/source_category_report/views/source-category-report-preview.html

[SDESK-3312](fix): Typos in form labels

[SDESK-3301](fix): Date filters showing 'Invalid Date'

---

client/content_publishing_report/controllers/ContentPublishingReportController.js
client/content_publishing_report/controllers/index.js
client/content_publishing_report/directives/ContentPublishingReportFilters.js
client/content_publishing_report/directives/ContentPublishingReportPreview.js
client/content_publishing_report/directives/index.js
client/content_publishing_report/index.js
client/content_publishing_report/services/ContentPublishingReports.js
client/content_publishing_report/services/index.js
client/content_publishing_report/views/content-publishing-report-chart-options.html
client/content_publishing_report/views/content-publishing-report-filters.html
client/content_publishing_report/views/content-publishing-report-panel.html
client/content_publishing_report/views/content-publishing-report-parameters.html
client/content_publishing_report/views/content-publishing-report-preview.html
client/index.js
server/analytics/__init__.py
server/analytics/common.py
server/analytics/content_publishing_report/__init__.py
server/analytics/content_publishing_report/content_publishing_report.py
server/features/content_publishing_report.feature

Requires PR https://github.com/superdesk/superdesk-analytics/pull/56 for generating Highcharts config

[SDESK-3183] Content Publishing Report

---

server/analytics/commands/send_schedule_reports_test.py
server/analytics/commands/send_scheduled_reports.py
server/analytics/emails/__init__.py
server/analytics/source_category_report.py

Depends on PR https://github.com/superdesk/superdesk-core/pull/1385

[SDESK-3319] Embed charts in the html body of scheduled report emails

---

client/directives/AnalyticsContainer.js
client/email_report/services/EmailReportService.js
client/saved_reports/services/SavedReportsService.js
client/scheduled_reports/directives/ScheduledReportsList.js
client/scheduled_reports/views/scheduled-reports-list.html

* Fix loading issue with Schedules and Saved reports causing recursive loop
* Deselect SavedReport when changing the ReportType
* Fix converting dates for saved reports
* Fix converting dates for manual email of schedules

[SDESK-3504](fix): Update ScheduleReports list when changing ReportType

---

client/charts/services/ChartConfig.js
client/charts/tests/ChartConfig.spec.js
client/content_publishing_report/controllers/ContentPublishingReportController.js
client/content_publishing_report/views/content-publishing-report-panel.html
client/publishing_performance_report/controllers/PublishingPerformanceReportController.js
client/publishing_performance_report/views/publishing-performance-report-panel.html
client/saved_reports/directives/SaveGenerateReport.js
client/scheduled_reports/directives/ReportScheduleInput.js
client/scheduled_reports/directives/ScheduledReportsList.js
client/source_category_report/controllers/SourceCategoryController.js
client/source_category_report/views/source-category-report-panel.html
server/analytics/base_report/__init__.py
server/analytics/chart_config/__init__.py
server/analytics/chart_config/chart_config_test.py
server/analytics/content_publishing_report/content_publishing_report.py
server/analytics/email_report/email_report.py
server/analytics/publishing_performance_report/publishing_performance_report.py
server/analytics/saved_reports.py

* (fix) etag issue when updating a SavedReport
* (fix) console error when viewing schedules set to hourly
Depends on PR https://github.com/superdesk/superdesk-analytics/pull/59

[SDESK-3496] Store gettext translations with the SavedReport

---

client/content_publishing_report/views/content-publishing-report-panel.html
client/directives/SourceFilters.js
client/publishing_performance_report/views/publishing-performance-report-panel.html
client/search/services/SearchReport.js
client/styles/analytics.scss
client/tests/sda-source-filters.spec.js
client/views/report-fitlers.html
server/analytics/base_report/__init__.py

Requires PR https://github.com/superdesk/superdesk-ui-framework/pull/274

[SDESK-3497] Exclude filters for ContentPublishing and PublishingPerformance reports

---

client/charts/directives/Chart.js
client/charts/services/ChartConfig.js
client/index.js
client/planning_usage_report/controllers/PlanningUsageReportController.js
client/planning_usage_report/controllers/index.js
client/planning_usage_report/directives/PlanningUsageReportPreview.js
client/planning_usage_report/directives/index.js
client/planning_usage_report/index.js
client/planning_usage_report/views/planning-usage-report-panel.html
client/planning_usage_report/views/planning-usage-report-parameters.html
client/planning_usage_report/views/planning-usage-report-preview.html
client/services/ReportsProvider.js
server/analytics/__init__.py
server/analytics/base_report/__init__.py
server/analytics/chart_config/__init__.py
server/analytics/common.py
server/analytics/planning_usage_report/__init__.py
server/analytics/planning_usage_report/planning_usage_report.py
server/analytics/planning_usage_report/planning_usage_report_test.py
server/analytics/reports/__init__.py
server/features/planning_usage_report.feature
server/requirements.txt
server/settings.py

Depends on PR https://github.com/superdesk/superdesk-analytics/pull/67

[SDESK-3534] Planning Usage Report

---

client/search/directives/SourceFilters.js
client/search/views/source-fitlers.html

* (fix): Filter out SearchProviders in IngestProvider filter list

[SDESK-3497](fix): Unable to select filters with less than 3 characters

---

client/charts/services/ChartConfig.js
client/charts/styles/charts.scss
client/charts/views/chart.html
client/desk_activity_report/controllers/DeskActivityReportController.js
client/desk_activity_report/controllers/index.js
client/desk_activity_report/directives/DeskActivityReportPreview.js
client/desk_activity_report/directives/index.js
client/desk_activity_report/index.js
client/desk_activity_report/views/desk-activity-report-panel.html
client/desk_activity_report/views/desk-activity-report-parameters.html
client/desk_activity_report/views/desk-activity-report-preview.html
client/index.js
client/search/directives/DateFilters.js
client/search/directives/PreviewDateFilter.js
client/search/services/SearchReport.js
client/search/tests/sda-preview-date-filter.spec.js
client/search/views/date-filters.html
client/search/views/preview-date-filter.html
client/utils.js
server/analytics/__init__.py
server/analytics/base_report/__init__.py
server/analytics/chart_config/__init__.py
server/analytics/desk_activity_report/__init__.py
server/analytics/desk_activity_report/desk_activity_report.py
server/analytics/stats/__init__.py
server/analytics/stats/archive_statistics.py
server/analytics/stats/common.py
server/analytics/stats/gen_archive_statistics.py
server/features/archive_history_stats/desk_transition_stats.feature
server/features/archive_history_stats/timeline_stats.feature

* Use elastic nested mapping for the different stat types
* Modify 'move' action to be 'move_from' and 'move_to' in stats.timeline
* Add new date filter 'relative_days'
* Improve style of table report and allow two header rows

[SDESK-3689] Desk Activity Report

---

server/analytics/commands/send_scheduled_reports.py

Related PR https://github.com/superdesk/superdesk-core/pull/1505

SDESK-3799 Cleanup and document commands in manage.py

---

client/charts/services/ChartConfig.js
client/charts/tests/ChartConfig.spec.js
client/publishing_performance_report/controllers/PublishingPerformanceReportController.js
client/search/tests/sda-preview-source-filter.spec.js

* Rearrange table heading order for PublishingPerformance report

[SDESK-4144] Change translations for item state

---

client/search/directives/UserSelect.js
client/search/directives/index.js
client/search/index.js
client/search/views/user-select.html
client/styles/analytics.scss
client/user_activity_report/views/user-activity-report-parameters.html

* Remove inactive/disabled users from the dropdown list

[SDESK-3947] Make user filters searchable

---

client/email_report/directives/EmailReportModal.js
client/email_report/views/email-report-modal.html
client/scheduled_reports/views/scheduled-reports-modal.html

* Should have been sda-report-preview-proxy

[SDESK-4197](fix) Incorrect directive name for sd-report-preview-proxy

---

client/search/directives/DateFilters.js

* gettext from client-core utilities is not available in 1.28

[SDESK-4148](fix) Don't import gettext from client-core

---

client/saved_reports/directives/SaveGenerateReport.js
package.json

- https://github.com/superdesk/superdesk-analytics/network/alerts

fix(packages): Update versions based on GitHub recommendations

---

client/index.js
client/services/ReportsProvider.js
client/services/tests/ReportProvider.spec.js

Depends on https://github.com/superdesk/superdesk-client-core/pull/3468

[SDESK-5234] Hide Analytics menu if no reports available

---

CHANGELOG.md
client/components/HighchartsLicense.tsx
package.json

Make the UI framework version match the client-core [here](https://github.com/superdesk/superdesk-cp-lji/blob/master/client/package.json#L5-L6)

Release 1.33.5
